### ISSUE TITLE
Error: _tkinter.TclError: no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by swzhangslg** [GoodAI/goodai-ltm-benchmark#140]
**Hi,** 

First of all, thank you for your amazing work on this project! It has been incredibly helpful and well-structured.

I'm encountering an issue when trying to run runner/run_benchmark.py using the tkinter library. The error message I'm receiving is:

`_tkinter.TclError: no display name and no $DISPLAY environment variable`

A possible cause might be that the remote server I'm using doesn't have a graphical interface. This environment likely lacks a display server, which might be causing the issue.

Could you please advise on how to resolve this? Is there a way to run the script in a headless mode or another recommended approach to bypass this error?

Thank you once again for your hard work and dedication to this project!

Best regards,
swzhangslg

**Comment by dcasbol** [comment]
We've just pushed [a fix for this](https://github.com/GoodAI/goodai-ltm-benchmark/blob/2ec33156b72fc2f7bd7d3768daea1cd72af71d36/runner/progress.py) and it will be included in the upcoming version. Thanks for the heads up!

**Comment by swzhangslg** [comment]
Hi David,

Thank you so much for your prompt response and for providing a workaround! I really appreciate the effort you and your team put into addressing this issue.

I apologize for the delay in getting back to you. I've been occupied with some other pressing matters over the past couple of days, so I haven’t had a chance to try out the dummy class solution you suggested. However, I'm glad to hear that you've already pushed a fix, and I’m looking forward to trying it out.

Thanks again for your support and for the excellent work on this project!

Cheers,
swzhangslg
